### ISSUE TITLE
older broker fails to bind

### ISSUE THREAD

**Issue by jaymccon** [fusor/ansible-asb-modules#12]
using an older broker results in apb's failing to bind with the error:

```
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Error attempting to get name/namespace from environment: 'POD_NAME'"}
```

This can be reproduced by building an apb using
`FROM ansibleplaybookbundle/apb-base:latest` in the Dockerfile and using docker.io/awsservicebroker/aws-service-broker:latest image (based on ansible service broker at the time of origin 3.7 release). 

From what I can see it looks like the issue was introduced in https://github.com/ansibleplaybookbundle/ansible-asb-modules/commit/a81eac248751ac6bf853277e10531c909155f75e it might be better to try to get the name/namespace and if that fails revert to the old bind behavior.

**Comment by rthallisey** [comment]
The bind credential method changed after 3.7 to using a secret to store bind-creds.  There's a published apb-base image with the tag release-1.0 you can use.

**Comment by jwmatthews** [comment]
@djzager is taking a look to see if there a nice way we can make the change be backwards compatible so newer apb base can continue to work with the 3.7 released broker.

Expect to have a better idea tomorrow, will update issue with our thoughts.

As a fallback, the workaround is as @rthallisey suggests to use an older tag for apb-base, which is same path @jaymccon is using for the AWS APBs currently.

**Comment by djzager** [comment]
If we want to make new APBs compatible with older brokers we'll need to make a few changes.

1. Add back some of the removed scripts from https://github.com/ansibleplaybookbundle/apb-base/pull/7/files . The entrypoint script will need to hold the logic on whether or not to exit. I suspect the best way to do this is on the `POD_NAME` and `POD_NAMESPACE` environment variables, if they have not been set, it must be an older broker and we need to wait for the broker to get the bind-credentials (this could cause unintended side-effects when the APB is `docker run`).
1. Add logic to https://github.com/ansibleplaybookbundle/ansible-asb-modules/blob/master/library/asb_encode_binding.py#L71 to either write to a file or create a secret based on the existence of the `POD_NAME`|`POD_NAMESPACE` environment variables.

**Comment by djzager** [comment]
When we do (2) from above, we'll also need to update https://github.com/ansibleplaybookbundle/ansible-asb-modules/pull/11 to also update the last operation to handle an older broker also.

**Comment by djzager** [comment]
@jaymccon You are correct with the change that is causing issues for you. Currently, APB's with a [runtime version of "2"](https://github.com/ansibleplaybookbundle/apb-base/blob/master/Dockerfile-latest#L3) are not supported for use with a [`release-1.0`](https://github.com/openshift/ansible-service-broker/tree/release-1.0) broker. If you look at our [ansible-service-broker deployment template](https://github.com/openshift/ansible-service-broker/blob/release-1.0/templates/deploy-ansible-service-broker.template.yaml#L493-L496) you can see that we have locked down that branch to only use APBs with the `release-1.0` tag for this reason.

As @rthallisey so quickly pointed out, the best solution is for APBs targeting a `release-1.0` broker that you are building now should use the [`docker.io/ansibleplaybookbundle/apb-base:release-1.0`](https://hub.docker.com/r/ansibleplaybookbundle/apb-base/tags/) image. You can accomplish this by modifying the impacted APB's Dockerfile:

```diff
diff --git a/Dockerfile b/Dockerfile
--- a/Dockerfile
+++ b/Dockerfile
@@ -1,20 +1,21 @@
-FROM ansibleplaybookbundle/apb-base
+FROM ansibleplaybookbundle/apb-base:release-1.0
```

Please, let me know if you have any issues making use of the `release-1.0` apb-base.
