### ISSUE TITLE
ansibleplaybookbundle.asb-modules is not in ansible-galaxy

### ISSUE THREAD

**Issue by johnkim76** [fusor/ansible-asb-modules#13]
Following the installation instruction (ansible-galazy install ...) fails.  It appears that this failure occurs because ansibleplaybookbundle.asb-modules is not in https://galaxy.ansible.com

**Comment by rthallisey** [comment]
Looks like it disappeared. Just re added it.
https://galaxy.ansible.com/ansibleplaybookbundle/asb-modules/
